name: GitHub Trophies

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@v2.0.0
        with:
          username: shreeyadav06
          token: ${{ secrets.PAT_TOKEN }}
          theme: darkhub
          output_path: assets/trophy.svg

      - name: Commit & Push Trophies
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github trophies"
          file_pattern: "assets/trophy.svg"

